// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.19.4
// source: pkg/card/pb/card.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddLevelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level  int32 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	UserId int32 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *AddLevelRequest) Reset() {
	*x = AddLevelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_card_pb_card_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLevelRequest) ProtoMessage() {}

func (x *AddLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_card_pb_card_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLevelRequest.ProtoReflect.Descriptor instead.
func (*AddLevelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_card_pb_card_proto_rawDescGZIP(), []int{0}
}

func (x *AddLevelRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *AddLevelRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AddLevelResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error  string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AddLevelResponse) Reset() {
	*x = AddLevelResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_card_pb_card_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLevelResponse) ProtoMessage() {}

func (x *AddLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_card_pb_card_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLevelResponse.ProtoReflect.Descriptor instead.
func (*AddLevelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_card_pb_card_proto_rawDescGZIP(), []int{1}
}

func (x *AddLevelResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AddLevelResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_card_pb_card_proto protoreflect.FileDescriptor

var file_pkg_card_pb_card_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x61,
	0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x3f,
	0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x40, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x32, 0x4a, 0x0a, 0x0b, 0x43, 0x61, 0x72, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3b, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x15, 0x2e, 0x63,
	0x61, 0x72, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a,
	0x0d, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x61, 0x72, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_card_pb_card_proto_rawDescOnce sync.Once
	file_pkg_card_pb_card_proto_rawDescData = file_pkg_card_pb_card_proto_rawDesc
)

func file_pkg_card_pb_card_proto_rawDescGZIP() []byte {
	file_pkg_card_pb_card_proto_rawDescOnce.Do(func() {
		file_pkg_card_pb_card_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_card_pb_card_proto_rawDescData)
	})
	return file_pkg_card_pb_card_proto_rawDescData
}

var file_pkg_card_pb_card_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_card_pb_card_proto_goTypes = []interface{}{
	(*AddLevelRequest)(nil),  // 0: card.AddLevelRequest
	(*AddLevelResponse)(nil), // 1: card.AddLevelResponse
}
var file_pkg_card_pb_card_proto_depIdxs = []int32{
	0, // 0: card.CardService.AddLevel:input_type -> card.AddLevelRequest
	1, // 1: card.CardService.AddLevel:output_type -> card.AddLevelResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_card_pb_card_proto_init() }
func file_pkg_card_pb_card_proto_init() {
	if File_pkg_card_pb_card_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_card_pb_card_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLevelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_card_pb_card_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLevelResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_card_pb_card_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_card_pb_card_proto_goTypes,
		DependencyIndexes: file_pkg_card_pb_card_proto_depIdxs,
		MessageInfos:      file_pkg_card_pb_card_proto_msgTypes,
	}.Build()
	File_pkg_card_pb_card_proto = out.File
	file_pkg_card_pb_card_proto_rawDesc = nil
	file_pkg_card_pb_card_proto_goTypes = nil
	file_pkg_card_pb_card_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CardServiceClient is the client API for CardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CardServiceClient interface {
	AddLevel(ctx context.Context, in *AddLevelRequest, opts ...grpc.CallOption) (*AddLevelResponse, error)
}

type cardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCardServiceClient(cc grpc.ClientConnInterface) CardServiceClient {
	return &cardServiceClient{cc}
}

func (c *cardServiceClient) AddLevel(ctx context.Context, in *AddLevelRequest, opts ...grpc.CallOption) (*AddLevelResponse, error) {
	out := new(AddLevelResponse)
	err := c.cc.Invoke(ctx, "/card.CardService/AddLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardServiceServer is the server API for CardService service.
type CardServiceServer interface {
	AddLevel(context.Context, *AddLevelRequest) (*AddLevelResponse, error)
}

// UnimplementedCardServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCardServiceServer struct {
}

func (*UnimplementedCardServiceServer) AddLevel(context.Context, *AddLevelRequest) (*AddLevelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLevel not implemented")
}

func RegisterCardServiceServer(s *grpc.Server, srv CardServiceServer) {
	s.RegisterService(&_CardService_serviceDesc, srv)
}

func _CardService_AddLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardServiceServer).AddLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/card.CardService/AddLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardServiceServer).AddLevel(ctx, req.(*AddLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CardService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "card.CardService",
	HandlerType: (*CardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLevel",
			Handler:    _CardService_AddLevel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/card/pb/card.proto",
}
